---
vpn_static_server:
COUNTRY:  "{{ lookup('file', '/etc/vpnconf/COUNTRY') }}"
PROVINCE:  "{{ lookup('file', '/etc/vpnconf/PROVINCE') }}"
CITY: "{{ lookup('file', '/etc/vpnconf/CITY') }}"
ORGANISATION: "{{ lookup('file', '/etc/vpnconf/ORGANISATION') }}"
EMAIL:  "{{ lookup('file', '/etc/vpnconf/EMAIL') }}"
ip_client:  "{{ lookup('file', '/home/cloud/config/ip_client') }}"
client_cidr: "{{ lookup('file', '/home/cloud/config/client_cidr.tmp') }}"
server_cidr: "{{ lookup('file', '/home/cloud/config/server_cidr.tmp') }}"
server_cidr_gw: "{{ lookup('file', '/home/cloud/config/server_cidr_gw.tmp') }}"
server_cidr_gw_df: "{{ lookup('file', '/home/cloud/config/server_cidr_gw_df.tmp') }}"
client_cidr_gw: "{{ lookup('file', '/home/cloud/config/client_cidr_gw.tmp') }}"
